Create download.py
syasini/AstroPaint pull request #60
Opened 2020-07-19 23:35 UTC by S-KSM

the initial commitment of the download module. #Needs to be tested!

2020-07-19 23:42 UTC, syasini commented
Awesome! Thanks Shobeir. I'm gonna check out the code in a second.

2020-07-19 23:43 UTC, syasini commented on astropaint/lib/download.py
> +__email__ = "yasini@usc.edu"
Add your name here! :)

2020-07-20 00:01 UTC, syasini requested changes

2020-07-20 00:01 UTC, syasini commented on astropaint/lib/download.py
> +
can you add a single-line comment briefly explaining what this does? 
Does it show a progress bar for the download?!

2020-07-20 00:01 UTC, syasini commented on astropaint/lib/download.py
> +                "WebSky_2x2" : 'https://media.githubusercontent.com/media/syasini/AstroPaint/master/astropaint/data/WebSky_2x2111.csv',
is the 111 at the end a typo?!

2020-07-20 00:01 UTC, syasini commented on astropaint/lib/download.py
> +        "WebSky_2x2" : 'https://media.githubusercontent.com/media/syasini/AstroPaint/master/astropaint/data/WebSky_2x2111.csv',
Same here! I think the ending should just be WebSky_2x2.csv.

2020-07-20 00:01 UTC, syasini commented on astropaint/lib/download.py
> +            if ~ os.path.exists(file_location):
This looks great! 
It's not gonna work though:
The files are always going to exist in the directory. If the repo is cloned with Git LFS, the files are going to be downloaded automatically (so there won't be a need for this function). But if the user doesn't have Git LFS, the files will still be there but will be basically empty. 

So one way around this would be to check for the size of the file (say if it's less than 1 MB then download), or just always overwrite when the function is used.

2020-07-20 00:01 UTC, syasini commented on astropaint/lib/download.py
> +            _get_dataset(ds_name,ds_url, file_location)
it looks like ds_name and ds_url are defined outside the previous for loop. Does this run?

2020-07-20 00:07 UTC, syasini commented
Fantastic job Shobeir 👏 Thanks for putting this together so fast. 

Can you do me a favor and merge this into `develop` instead of `master`? I only update `master` from `develop` to make sure it doesn't accidentally break, especially now that I don't have a lot of tests.

2020-07-20 00:56 UTC, S-KSM commented
Yes to all! And the comments make sense! :)

On Sun, Jul 19, 2020, 8:07 PM Siavash Yasini <notifications@github.com>
wrote:

> Fantastic job Shobeir 👏 Thanks for putting this together so fast.
>
> Can you do me a favor and merge this into develop instead of master? I
> only update master from develop to make sure it doesn't accidentally
> break, especially now that I don't have a lot of tests.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/syasini/AstroPaint/pull/60#issuecomment-660732050>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEWSEGNPULOWWIZY463JZJDR4ODFJANCNFSM4PBU7W4A>
> .
>

2020-07-22 06:35 UTC, S-KSM commented on astropaint/lib/download.py
> +                "WebSky_2x2" : 'https://media.githubusercontent.com/media/syasini/AstroPaint/master/astropaint/data/WebSky_2x2111.csv',
These 111s were created by a parrot while I left my keyboard!

2020-09-21 21:06 UTC, closed without merging